---
- name: Install NGINX
  hosts: web
  roles:
    - role: nginxinc.nginx
    - role: firewall
      vars:
        firewall_custom_rules:
          - '80'
          - '443'
  vars:
    nginx_type: opensource
    nginx_install_from: nginx_repository
    nginx_branch: stable

- name: Harden NGINX
  hosts: web
  roles:
    # One of the step included openssl dhparam that really take a while.
    # It is recommended to create the dhparam file manually on a powerful PC and then upload it to the Raspberry Pi
    - devsec.hardening.nginx_hardening
  vars:
    nginx_dh_size: 4096
