---
- name: Harden OS
  hosts: all
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening

- name: Harden SSH
  hosts: all
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.ssh_hardening
  vars:
    ssh_permit_root_login: no
    ssh_server_ports:
      - "22"
