---
- name: Set up administrator user and minimum system packages
  hosts: all
  roles:
    - common

- name: Harden OS
  hosts: all
  roles:
    - devsec.hardening.os_hardening
  vars:
    sysctl_overwrite:
      # Default value on DietPi that runs on Raspberry Pi 3 B+
      vm.mmap_rnd_bits: 18

- name: Harden SSH
  hosts: all
  roles:
    - devsec.hardening.ssh_hardening
  vars:
    ssh_permit_root_login: "no"
    ssh_server_ports:
      - "22"

- name: Install NGINX
  hosts: all
  roles:
    - nginxinc.nginx
  vars:
    nginx_type: opensource
    nginx_install_from: nginx_repository
    nginx_branch: stable

- name: Harden NGINX
  hosts: all
  roles:
    # One of the step included openssl dhparam that really take a while.
    # It is recommended to create the dhparam file manually on a powerful PC and then upload it to the Raspberry Pi
    - devsec.hardening.nginx_hardening
