---
- name: Install Podman package
  ansible.builtin.apt:
    name: "{{ podman_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Ensure global systemd Quadlet configuration directory exists
  ansible.builtin.file:
    path: /etc/containers/systemd
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Allow UFW routed traffic for Podman bridge interface (inbound)
  community.general.ufw:
    rule: allow
    direction: in
    interface: "{{ podman_bridge_interface }}"
    route: true

- name: Allow UFW routed traffic for Podman bridge interface (outbound)
  community.general.ufw:
    rule: allow
    direction: out
    interface: "{{ podman_bridge_interface }}"
    route: true
