---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
  labels:
    app.kubernetes.io/name: rancher
    app.kubernetes.io/instance: rancher-rabbithouse
    app.kubernetes.io/managed-by: kubectl