---
- name: Install system packages
  ansible.builtin.apt:
    name:
      - curl
      - git
      - neovim
      - python3-apt
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    state: present
