---
- name: Create default, non-root administrator user
  ansible.builtin.user:
    name: "{{ user_username }}"
    password: "!" # Use public SSH key authentication
    create_home: yes
    shell: /bin/bash
    groups:
      - adm
      - sudo
      - staff
    state: present
- name: Add SSH public key to the administrator user
  ansible.posix.authorized_key:
    user: "{{ user_username }}"
    key: "{{ user_public_key }}"
    state: present
- name: Grant passwordless sudo to the administrator user
  community.general.sudoers:
    name: admin
    user: "{{ user_username }}"
    nopassword: true
    commands: ALL
    state: present
