---
apiVersion: v1
kind: Namespace
metadata:
  name: mcp
  labels:
    app.kubernetes.io/name: mcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: context7-deployment
  namespace: mcp
  labels:
    app.kubernetes.io/name: context7
    app.kubernetes.io/instance: context7-rabbithouse
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/version: latest
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: context7
      app.kubernetes.io/instance: context7-rabbithouse
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: context7
        app.kubernetes.io/instance: context7-rabbithouse
        app.kubernetes.io/managed-by: kubectl
        app.kubernetes.io/version: latest
    spec:
      containers:
        - name: context7
          image: docker.io/mcp/context7:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: context7-service
  namespace: mcp
  labels:
    app.kubernetes.io/name: context7
    app.kubernetes.io/instance: context7-rabbithouse
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/version: latest
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: context7
    app.kubernetes.io/instance: context7-rabbithouse
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 8080
